# -*- coding: utf-8 -*-
"""Project #2-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KSfKj47_K_nZ9TVgsOQsKu1OXrX6BRTC
"""

import pandas as pd
from pandas import Series, DataFrame
import numpy as np

data = pd.read_csv('2019_kbo_for_kaggle_v2.csv')

#1
def top10(x, year):
  data_x_all = data.loc[:, ['batter_name', 'H', 'avg', 'HR', 'OBP', 'year']][data['year'] == year]
  data_x = data_x_all[['batter_name', x.name]]
  sorted_array_10 = data_x.sort_values(by = x.name, ascending=False)[:10]
  sorted_name = sorted_array_10['batter_name']
  sorted_name.index = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  return sorted_name

print('\t\t\t2015\n', data[['H', 'avg', 'HR', 'OBP']].apply(top10, year = 2015))

print('\t\t\t2016\n', data[['H', 'avg', 'HR', 'OBP']].apply(top10, year = 2016))

print('\t\t\t2017\n', data[['H', 'avg', 'HR', 'OBP']].apply(top10, year = 2017))

print('\t\t\t2018\n', data[['H', 'avg', 'HR', 'OBP']].apply(top10, year = 2018))

#2
data_all = data[['batter_name','war', 'cp', 'year']][data['year'] == 2018]
position = ['포수', '1루수', '2루수', '3루수', '유격수', '좌익수', '중견수', '우익수']
data_top = []
for i in position:
  data_i = data_all[data_all['cp'] == i]
  top_war = data_i['war'].sort_values(ascending = False).iloc[0]
  name = data_i[data_i['war'] == top_war]['batter_name'].iloc[0]
  data_top.append(name)

print('\n', pd.Series(data_top, index = position))

#3
data_ = data[['R', 'H', 'HR', 'RBI', 'SB', 'war', 'avg', 'OBP', 'SLG', 'salary']]

data_corr = data_.corrwith(data_.salary).drop('salary')

print('\nsalary와 상관계수가 가장 높은 변수:', data_corr.idxmax())

